module.exports = [
  {
    name: "tanu saini",
    email: "tanu.saini@example.com",
    gender: "female",
    password: "password1",
    dob: new Date("1990-01-01"),
    username: "tanu_saini",
  },
  {
    name: "rohit kumar",
    email: "rohit.kumar@example.com",
    gender: "male",
    password: "password2",
    dob: new Date("1992-02-02"),
    username: "rohit_kumar",
  },
  {
    name: "meera kapoor",
    email: "meera.kapoor@example.com",
    gender: "female",
    password: "password3",
    dob: new Date("1993-03-03"),
    username: "meera_kapoor",
  },
  {
    name: "ashok singh",
    email: "ashok.singh@example.com",
    gender: "male",
    password: "password4",
    dob: new Date("1988-04-04"),
    username: "ashok_singh",
  },
  {
    name: "priya sharma",
    email: "priya.sharma@example.com",
    gender: "female",
    password: "password5",
    dob: new Date("1995-05-05"),
    username: "priya_sharma",
  },
  {
    name: "rahul verma",
    email: "rahul.verma@example.com",
    gender: "male",
    password: "password6",
    dob: new Date("1991-06-06"),
    username: "rahul_verma",
  },
  {
    name: "aarti jain",
    email: "aarti.jain@example.com",
    gender: "female",
    password: "password7",
    dob: new Date("1994-07-07"),
    username: "aarti_jain",
  },
  {
    name: "vijay rao",
    email: "vijay.rao@example.com",
    gender: "male",
    password: "password8",
    dob: new Date("1989-08-08"),
    username: "vijay_rao",
  },
  {
    name: "neha mehta",
    email: "neha.mehta@example.com",
    gender: "female",
    password: "password9",
    dob: new Date("1996-09-09"),
    username: "neha_mehta",
  },
  {
    name: "ravi patel",
    email: "ravi.patel@example.com",
    gender: "male",
    password: "password10",
    dob: new Date("1987-10-10"),
    username: "ravi_patel",
  },
  {
    name: "riya sen",
    email: "riya.sen@example.com",
    gender: "female",
    password: "password11",
    dob: new Date("1992-11-11"),
    username: "riya_sen",
  },
  {
    name: "amit choudhary",
    email: "amit.choudhary@example.com",
    gender: "male",
    password: "password12",
    dob: new Date("1985-12-12"),
    username: "amit_choudhary",
  },
  {
    name: "alka yadav",
    email: "alka.yadav@example.com",
    gender: "female",
    password: "password13",
    dob: new Date("1993-01-13"),
    username: "alka_yadav",
  },
  {
    name: "gaurav bhatt",
    email: "gaurav.bhatt@example.com",
    gender: "male",
    password: "password14",
    dob: new Date("1986-02-14"),
    username: "gaurav_bhatt",
  },
  {
    name: "mohit tiwari",
    email: "mohit.tiwari@example.com",
    gender: "male",
    password: "password15",
    dob: new Date("1990-03-15"),
    username: "mohit_tiwari",
  },
  {
    name: "kavita pandey",
    email: "kavita.pandey@example.com",
    gender: "female",
    password: "password16",
    dob: new Date("1991-04-16"),
    username: "kavita_pandey",
  },
  {
    name: "deepak malhotra",
    email: "deepak.malhotra@example.com",
    gender: "male",
    password: "password17",
    dob: new Date("1989-05-17"),
    username: "deepak_malhotra",
  },
  {
    name: "suman gupta",
    email: "suman.gupta@example.com",
    gender: "female",
    password: "password18",
    dob: new Date("1992-06-18"),
    username: "suman_gupta",
  },
  {
    name: "anil joshi",
    email: "anil.joshi@example.com",
    gender: "male",
    password: "password19",
    dob: new Date("1988-07-19"),
    username: "anil_joshi",
  },
  {
    name: "pooja rao",
    email: "pooja.rao@example.com",
    gender: "female",
    password: "password20",
    dob: new Date("1995-08-20"),
    username: "pooja_rao",
  },
];
